[project]
name = "pp-labeler"
version = "0.1.0"
requires-python = ">=3.10,<3.12"
dependencies = [
    "accelerate>=1.11.0",
    "atproto>=0.0.63",
    "langdetect>=1.0.9",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.7.2",
    "sentencepiece>=0.2.1",
    "tokenizers>=0.22.1",
    "torch>=2.9.1",
    "transformers>=4.57.1",
]

[tool.uv]
dev-dependencies = []
